spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
#server:
#  servlet:
#    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method

jwt:
  secret: ${secret_key}
  access-token-validity: 7200000 # 2 hour
  refresh-token-validity: 86400000 # 1 week

kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${REDIRECT_URI}
  token_uri: "https://kauth.kakao.com" # 토큰 발급 요청 URI
  user_info_uri: "https://kapi.kakao.com" # 사용자 정보 요청 URI