spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method

jwt:
  secret: ${secret_key}
  accessTokenValidity: 7200000 # 2 hour
  refreshTokenValidity: 604800000 # 1 week

kakao:
  client-id: ${REST_API_KEY}
  redirect-uri: ${REDIRECT_URI}
  token-uri: "https://kauth.kakao.com/oauth/token" # 토큰 발급 요청 URI
  user-info-uri: "https://kapi.kakao.com/v2/user/me" # 사용자 정보 요청 URI